### ISSUE TITLE
InstantiateCC fails

### ISSUE THREAD

**Issue by ushakrishnan** [asararatnakar/NodeApp_1_2#2]
Postman calls passed until InstantiateCC.  

When InstantiateCC is called, I show the following error on terminal -

`[2018-11-30 22:59:31.672] [ERROR] instantiate-upgrade-chaincode - instantiate proposal was bad
[2018-11-30 22:59:31.673] [ERROR] instantiate-upgrade-chaincode - undefined
[2018-11-30 22:59:31.673] [DEBUG] instantiate-upgrade-chaincode - Failed to send Proposal and receive all good ProposalResponse
[2018-11-30 22:59:31.673] [ERROR] instantiate-upgrade-chaincode - Failed to instantiate. cause:Failed to send Proposal and receive all good ProposalResponse
(node:30063) UnhandledPromiseRejectionWarning: Error: Failed to instantiate. cause:Failed to send Proposal and receive all good ProposalResponse
    at Object.instantiateUpdgradeChaincode (/Users/ushakrishnan/Go/src/github.com/hyperledger/NodeApp_1_2/app/instantiate-upgrade-chaincode.js:217:9)
    at <anonymous>
(node:30063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)`

I Installed CC with a different chaincode and it goes well until again InstantiateCC. 

My docker logs shows  (wrong folder path?) -

`2018-12-01 04:48:17.529 UTC [lscc] executeDeployOrUpgrade -> ERRO 05d cannot get package for chaincode (mycc:v4)-err:open /var/hyperledger/production/chaincodes/mycc.v4: no such file or directory
`

**Comment by ushakrishnan** [comment]
https://github.com/asararatnakar/NodeApp_1_2/blob/master/app/instantiate-upgrade-chaincode.js function call below has parms ( functionName, chaincodeType) switched, but that does not fix the issue.  But at least lends to a different error in docker logs!

`var instantiateUpdgradeChaincode = async function(peers, channelName, chaincodeName, chaincodeVersion, functionName, chaincodeType, args, username, org_name, isUpgrade) {`

**Comment by asararatnakar** [comment]
@ushakrishnan So did you installed the chaincode with version **v4** from Postman ?
Those logs indicates chaincode installation is not successful. could you paste the peer logs ?

**Comment by ushakrishnan** [comment]
Command line log and peer docker logs - https://www.dropbox.com/sh/h0z3r9qjha3i1jd/AABXZuf7Bl5jVTjR845PSswDa?dl=0

- Postman (using newman v4) - fails at create channel
- end2end.sh fails during instantiate (or create?)

Logs include both above cases

**Comment by ushakrishnan** [comment]
Fixed!  
Issue: (Possible) Lack of permissions somewhere deep in the folder (although sh commands on main folders did not show evidence of issues). 
OS: macOS 
Fix: run script 
> chmod -R 777 directory
